### ISSUE TITLE
Config Flow has no labels

### ISSUE THREAD

**Issue by seanmccabe** [sh00t2kill/HA-Bring-ToDo-List#11]
Doing the initial config flow, there are no labels on the input fields.

![image](https://github.com/sh00t2kill/HA-Bring-ToDo-List/assets/12243212/c902216b-0859-460a-8c44-94cd28d4d28c)

**Comment by sh00t2kill** [comment]
yeah -- i dont know what i broke and cant work out how to fix it!

**Comment by sh00t2kill** [comment]
Oh! Its funny what happens when you look with fresh eyes.

I deleted the strings,json file.
Should be fixed in 1.4.1

![image](https://github.com/sh00t2kill/HA-Bring-ToDo-List/assets/38101689/adb860d8-db2b-4070-bba2-3bd9892ea6bb)
