### ISSUE TITLE
Hide checked

### ISSUE THREAD

**Issue by rafinesse** [sh00t2kill/HA-Bring-ToDo-List#3]
Thanks, addon is working fine. Any chance we can hide checked items?

**Comment by sh00t2kill** [comment]
Once an item is checked, you can delete it by pressing the button at the top of the checked items.
![image](https://github.com/sh00t2kill/HA-Bring-ToDo-List/assets/38101689/51425e1f-6cd4-4ff9-848d-ebb7061e7189)

Does this work differently to how an inbuilt todo list works ?

**Comment by teranex** [comment]
I was also wondering tihs. The problem wit clearing them is that it also removes them from the recently used list in Bring itself, which might be handy to have around.

**Comment by sh00t2kill** [comment]
I see your point, but I'm not really sure how to implement it and still keeping HA and bring in sync.

I've "assumed" a checked item in HA and a recent item in bring is the same thing.

Alternatively, items could be immediately removed from HA when checked, and recent items then not in HA at all, but this isn't really ideal either.

I had to make a decision one way or the other. If an item was cleared in HA, and not removed from the recent list in bring, it would end up coming back again at the next periodic sync.

I'm open to ideas, just can't see a better way to make this work and always remain in sync

**Comment by teranex** [comment]
@sh00t2kill I completely follow your logic and it seems reasonable. My first idea was actually to look for an option in the to-do list card to hide completed items, as I see this more as a front-end issue rather than something an integration should handle

**Comment by sh00t2kill** [comment]
Todd is still very new.
I'd expect custom cards to start appearing soon

**Comment by sh00t2kill** [comment]
@rafinesse potentially 2023.12.x introduces this!
