### ISSUE TITLE
Editing and item results in an error message

### ISSUE THREAD

**Issue by teranex** [sh00t2kill/HA-Bring-ToDo-List#4]
Steps to reproduce:

1. Add 'cheese'
1. try to chance it to 'cheese: 2' or 'Cheese'

Error:
Failed to call service todo/update_item. BringTodoItem(summary='test:1', uid='ee54c88b-9999-444e-a648-26f0fcadbcdc_item_test:1', status=<TodoItemStatus.COMPLETED: 'completed'>) is not in list

**Comment by MikeDeltaHH** [comment]
Same error here when i add or edit an item!

**Comment by sh00t2kill** [comment]
Fair -- thats not going to work in the current implementation.
Ill have a think about the best way to tackle that. There is some strange logic at play in order to keep the 2 services in sync.

Does it update in Bring, and HA is keeping the old item information ?
Does it then eventually catch up on the next sync (ie in 30 seconds?)

**Comment by MikeDeltaHH** [comment]
Hi!
The list is updated, despite the error message. I have the additional problem that after a while 4 of the 6 lists are no longer available as entities - I have to restart HA every time, then it works again...

**Comment by sh00t2kill** [comment]
@MikeDeltaHH are you able to please create a seperate issue for that, as this isnt related to the editing issue.
Please turn on debug logging and provide logs around the time it dissapears as thats not something I have experienced or had reported.

**Comment by MikeDeltaHH** [comment]
Yes, i will do that - and thanks for your work at this integration! :)

**Comment by sh00t2kill** [comment]
I have just released 1.3.1-beta, which in my testing addresses the issue of an item being edited, rather than just checked or unchecked.

**Comment by teranex** [comment]
> I have just released 1.3.1-beta, which in my testing addresses the issue of an item being edited, rather than just checked or unchecked.

I tested this:
- I first added 'Kaas' (Cheese in Dutch) to the list from HA (still on 2023.11.3)
- Item is correctly added to Bring
- Then I changed it to 'Kaasjes' (small cheeses) from HA
- 'Kaas' is correctly removed in Bring, 'Kaasjes' is correctly added in Bring
- but then I have 'Kaasjes' twice in the HA list
- then I renamed one of the two back to 'Kaas' from HA
- Kaasjes is correctly renamed to Kaas in Bring + the second 'Kaasjes' also dissapears from the HA list, leaving only the renamed 'Kaas' in the HA list

So already an improvement :). Could it be that, after renaming an item, the list is fetched again from Bring, which now also includes the newly added item which is then added again to HA resulting in the duplicate item, something like that?

**Comment by sh00t2kill** [comment]
Yeah, it could be. 

I didn't have the same experience when doing a very similar test, but it's possibly a timing issue (ie it was updating in the background at the same time) or it could be an issue with translations as I didn't test with a translated item. 

If you do something really random, like create a list item called "a thing" and then rename it to "another thing" do you get the same experience?

I'm out at the moment but can look at it again tomorrow.

**Comment by teranex** [comment]
> If you do something really random, like create a list item called "a thing" and then rename it to "another thing" do you get the same experience?
> 

tested this exact scenario and then I also end up with two 'another thing' entries, similar to my earlier example in https://github.com/sh00t2kill/HA-Bring-ToDo-List/issues/4#issuecomment-1844780769

**Comment by sh00t2kill** [comment]
OK cool at least that rules out the translation being a problem. Will do some more testing.

**Comment by sh00t2kill** [comment]
@teranex I was able to replicate the issue. Turns out i was not waiting long enough after editing an item to see the next update from Bring create the duplicate.

I believe v1.3.3-beta should address the issue. Ive done quite a bit of testing and am no longer getting any duplicates.

**Comment by teranex** [comment]
> @teranex I was able to replicate the issue. Turns out i was not waiting long enough after editing an item to see the next update from Bring create the duplicate.
> 
> I believe v1.3.3-beta should address the issue. Ive done quite a bit of testing and am no longer getting any duplicates.

I have tested this version and it does indeed seem to fix it :). Thanks a lot!

**Comment by sh00t2kill** [comment]
Thanks for confirming. 
Change merged and v1.3.3 released.
