### ISSUE TITLE
Feature Request: Provide service call for synchronizing with Bring

### ISSUE THREAD

**Issue by jkrenzer** [sh00t2kill/HA-Bring-ToDo-List#5]
Hi!

I'd like to suggest a service call like in the old shopping_list integration to be able to sync Bring and HA manually or from an automation.

Cheers,

Jörn

**Comment by sh00t2kill** [comment]
Hi @jkrenzer to what end ?
This integration syncs automatically every 30 seconds, or immediately if you add or remove an item.

Im not sure what this would achieve ?

**Comment by jkrenzer** [comment]
- This way you could ensure an update in an event-driven way, e.g. when I ask assist to read the grocery list to me, it could pull to make sure the list is completen also from the bring side
- You could give impatient spouses a button to refresh 😆 or use this if both are shopping in parallel with HA and Bring

**Comment by sh00t2kill** [comment]
@jkrenzer apologies, i have this in a different branch i just need to do some more testing to make sure it works.

**Comment by sh00t2kill** [comment]
Released in 1.4.0
