### ISSUE TITLE
Fill the list via Google Home

### ISSUE THREAD

**Issue by diver77** [sh00t2kill/HA-Bring-ToDo-List#8]
Is there a way to fill the list in Homeassistant using Google home and this is then synchronized in Bring? Unfortunately, Google has prevented this possibility to "fill" Bring directly with Google Home. But maybe there is the possibility via Homeassistant. That would be really great, otherwise synchronizing the to-do list with Bring is unfortunately superfluous. I know that's not a mistake but a wish, but it's almost Christmas. :-)
Thanks for your help and have a Merry Christmas.
Greetings diver

**Comment by sh00t2kill** [comment]
I believe intents for todo lists are coming. This is a core HA feature and not something handled by this integration.
